title: Boko the Bobcat
description: Official Mascot of Texas State University
theme: jekyll-theme-cayman
show_downloads: false
social: true

# URLs
booking:
  link: #to be added


# Social Media
author: "Boko"
school: Texas State University
image: /Boko.png
twitter:
  username: TXSTBoko
instagram:
  username: TXSTBoko
snapchat:
  username: TXSTBoko
